# Do not edit. Generated by the configure script.
export PATH:=/home/rjloor/pasantiasPreprofesionales/VisualizaEspol/geopol/node-v11.10.1/out/tools/bin:$(PATH)
PYTHON=/usr/bin/python2.7
BUILDTYPE=Release
PREFIX=/home/rjloor/pasantiasPreprofesionales/pasantias
NODE_TARGET_TYPE=executable
